version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: johnDoe
        volumes:
            -  db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: john-doe-api
        restart: always
        build: ./john-doe
        ports:
            - "3000:3000"
        depends_on:
            - db
    web:
        container_name: john-doe-web
        restart: always
        build: ./web
        ports:
            - "3005:3000"
        depends_on:
            - db
volumes:
    db-data: